[package]
name = "tail_journald"
version = "0.1.0"
authors = ["Tobias Florek <tob@butter.sh>"]

[dependencies.systemd]
git = "https://github.com/ibotty/rust-systemd.git"
branch = "await-new-records"
version = "0.*"
